sudo: required

language: scala
# These should be match with cross build settings in sbt
scala:
   - 2.11.8
   - 2.12.1

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker pull redis
  - docker run -p 6379:6379 -d redis

script: sbt ++$TRAVIS_SCALA_VERSION test
